version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ls
  build:
    commands:
      - echo Build started on `date`
      - mvn -B clean package --file app/pom.xml
  post_build:
    commands:
      - java -jar /opt/veracode/api-wrapper.jar -action uploadandscan -vid $VID -vkey $VKEY -appname verademo -createprofile false -version $(date +%Y-%m-%d-%H:%M) -filepath app/target/verademo.war -sandboxname aws-codebuild -createsandbox true
artifacts:
  files:
    - app/target/verademo.war
