version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - ls
      - uname -a
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws configure set region us-east-1
      - VERACODE_KEY=$(aws ssm get-parameter --name VKEY --query "Parameter.Value" --output text)
      - VERACODE_ID=$(aws ssm get-parameter --name VID --query "Parameter.Value" --output text)
      - echo "$VERACODE_ID"
  build:
    commands:
      - echo Build started on `date`
      - mvn -B clean package --file app/pom.xml
      - java -jar /opt/veracode/api-wrapper.jar -vid $VERACODE_ID -vkey $VERACODE_KEY -action UploadAndScan -createprofile true -appname Verademo -version $(date +%Y-%m-%d-%H:%M)} -filepath app/target/verademo.war
      #- java -jar /opt/veracode/api-wrapper.jar -vid $VERACODE_ID -vkey $VERACODE_KEY -action UploadAndScan -createprofile true -appname Verademo -version $(date +%Y-%m-%d-%H:%M)} -filepath app/target/verademo.war
  post_build:
    commands:
      - echo post build step
artifacts:
  files:
    - app/target/verademo.war
