version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - ls
  build:
    commands:
      - echo Build started on `date`
      - mvn -B clean package --file app/pom.xml
  post_build:
    commands:
      - curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - unzip pipeline-scan-LATEST.zip pipeline-scan.jar
      - java -jar pipeline-scan.jar
        --veracode_api_id "$VID"
        --veracode_api_key "$VKEY"
        --file "app/target/verademo.war"
artifacts:
  files:
    - app/target/verademo.war
