gitProvider: github       # replace with your GitRepo integration name
gitIntegration: github
path: bnreplah/verademo  
gitRepositoryPath: bnreplah/verademo     # replace jfrog with your username or org name
artifactoryIntegration: github 

