name: SBOM generation

on: workflow_dispatch

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: Verademo

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get summary report
        run: |
          cd /tmp
          export VERACODE_API_KEY_ID=${{ env.API_ID }}
          export VERACODE_API_KEY_SECRET=${{ env.API_KEY }}
          GUID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }}" | jq -r '._embedded.applications[0].guid')
          http --auth-type veracode_hmac GET "https://api.veracode.com/srcclr/sbom/v1/targets/$GUID/cyclonedx?type=application" >> ${{ env.APP_NAME }}-SBOM.json
        
      - name: upload SBOM report
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: /tmp/${{ env.APP_NAME }}-SBOM.json


