name: SBOM generation

on: workflow_dispatch

env:
  API_ID: ${{ secrets.VERACODE_API_ID }}
  API_KEY: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: Verademo

jobs:

  get_summary_report:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    steps: 
      - name: get summary report
        run: |
          cd /tmp
          export VERACODE_API_KEY_ID=${{ env.API_ID }}
          export VERACODE_API_KEY_SECRET=${{ env.API_KEY }}
          ID=$(http --auth-type veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }}" | jq -r '._embedded.applications[0].id')
          echo GUID: ${ID}
          BUILD_ID=$(http --auth-type veracode_hmac GET "https://analysiscenter.veracode.com/api/5.0/getbuildinfo.do?app_id=$ID" | sed -n 's/.*build_id="\([0-9]*\)".*/\1/p')
          echo Build ID: $BUILD_ID
          http --auth-type veracode_hmac GET "https://api.veracode.com/srcclr/sbom/v1/targets/$ID/cyclonedx?type=application"
          http --auth-type=veracode_hmac "https://api.veracode.com/srcclr/sbom/v1/targets/${ID}/cyclonedx?type=application"
          ls
          cat ${{ env.APP_NAME }}-SBOM.json
        
      - name: upload SBOM report
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: /tmp/${{ env.APP_NAME }}-SBOM.json


