name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
  VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: Verademo
  APP_ID: ""
  
