name: Summary Report

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    workflow_dispatch: 

env:
  VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
  VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
  APP_NAME: Verademo
  APP_ID: ""
  


jobs: 
  veracode-api-call:
    runs-on: ubuntu-latest
    env:
        API_ID: ${{ secrets.VERACODE_API_ID }}
        API_KEY: ${{ secrets.VERACODE_API_KEY }}
    steps:
    - name: Get Application GUID for Verademo One
      id: get_guid
      run: |
        GUID=$(docker run --rm \
          -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
          -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v1/applications/?name=${{ env.APP_NAME }} \
          | jq -r '._embedded.applications[0].guid')
        echo "$GUID" > app_id.txt
        echo "APP_ID=$GUID" >> $GITHUB_ENV
        echo "$APP_ID"
        
        docker run --rm \
         -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
         -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/healthcheck/status

        
    - name: API Call
      id: api_call
      run: |
        docker run --rm \
         veracode/api-signing:cmd \
         -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
         -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/api/authn/v2/api_credentials
    - name: API_call_APP-ID
      id: api_call2
      run: |
        docker run --rm \
         -e VERACODE_API_KEY_ID=${{ env.API_ID }} \
         -e VERACODE_API_KEY_SECRET=${{ env.API_KEY }} \
          veracode/api-signing:cmd \
          http --auth-type veracode_hmac GET \
          https://api.veracode.com/appsec/v2/applications/${{env.APP_ID}}/summary_report
        
      
#    - name: set env creds
#      id: set_env
#      run: |
#        echo "APP_ID=$(cat app_id.txt)" >> $GITHUB_ENV

    
    
  
